"""Build docs/needs-eric.md: every screening decision that needs an operator action.

Usage: python3 scripts/haiku-batch/needs_eric.py
Reads every docs/pilot-screening/*.json batch. Lists (1) wrong-PDF identity mismatches, (2) DEGRADED
records (missing DOI or unreadable text) and (3) out-of-scope or editorial exclusions that are judgment
calls, each with the exact action to take.
"""
import glob, json, os, re

R = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
rows = []
for path in sorted(glob.glob(f"{R}/docs/pilot-screening/*.json")):
    data = json.load(open(path, encoding="utf8"))
    for r in data["records"]:
        if r["decision"] != "INCLUDE":
            rows.append((data["batchId"], r))

def short(text, n=260):
    text = re.sub(r"\s+", " ", text or "").strip()
    return text if len(text) <= n else text[: n - 3].rstrip() + "..."

IDENTITY = re.compile(r"identity mismatch|different article|^the pdf is a|^the local pdf contains", re.I)
mismatch = [(b, r) for b, r in rows if r["decision"] == "EXCLUDE" and IDENTITY.search(r.get("exclusionReason", ""))]
degraded = [(b, r) for b, r in rows if r["decision"] == "DEGRADED"]
scope = [(b, r) for b, r in rows if r["decision"] == "EXCLUDE" and (b, r) not in mismatch]

def is_unreadable(r):
    return re.search(r"unreadable|could not open|no readable|truncated|scanned|image-only", r.get("degradedReason", ""), re.I)

out = [
    "# Needs Eric",
    "",
    "Generated by `python3 scripts/haiku-batch/needs_eric.py` from every batch in `docs/pilot-screening/`. "
    "Regenerate after each batch. Nothing here is published until the action is done and the record goes "
    "through a new screening and synthesis batch.",
    "",
    f"| Group | Count |",
    f"|---|---|",
    f"| Wrong PDF on disk (identity mismatch) | {len(mismatch)} |",
    f"| DEGRADED: DOI not printed in the PDF | {sum(1 for _, r in degraded if not is_unreadable(r))} |",
    f"| DEGRADED: text unreadable or incomplete | {sum(1 for _, r in degraded if is_unreadable(r))} |",
    f"| Scope or editorial exclusions you may want to reverse | {len(scope)} |",
    "| Published records sharing a DOI | see section 5 |",
    "",
    "## 1. Wrong PDF on disk",
    "",
    "The file is named for one article but contains another. **Action:** download the article the filename names "
    "and replace the file in `SourcePapers/` (keep the filename). Then re-queue it with "
    "`prepare.py --files`. The misfiled article described in the note may be worth adding under its own name "
    "if it is not already in the library.",
    "",
]
for b, r in mismatch:
    out += [f"- **{r['sourceFile']}** ({b})", f"  - In the file instead: {short(r.get('exclusionReason'))}"]
out += [
    "",
    "## 2. DEGRADED: DOI not printed in the PDF",
    "",
    "The text is readable and the record was otherwise drafted, but the article's own DOI is not in the PDF, so "
    "it cannot be published under the house rule. **Action:** look up the DOI (and confirm the year) at the "
    "publisher or Crossref, then either replace the PDF with the publisher version that prints the DOI, or "
    "approve publishing with `doiVerification` set to the external source. A single batched Firecrawl or "
    "Crossref lookup can resolve all of these at once if you approve it.",
    "",
]
for b, r in degraded:
    if not is_unreadable(r):
        out += [f"- **{r['sourceFile']}** ({b})", f"  - {short(r.get('degradedReason'))}"]
out += [
    "",
    "## 3. DEGRADED: text unreadable or incomplete",
    "",
    "**Action:** replace the file with a text-based PDF (or run OCR), then re-queue it.",
    "",
]
for b, r in degraded:
    if is_unreadable(r):
        out += [f"- **{r['sourceFile']}** ({b})", f"  - {short(r.get('degradedReason'))}"]
out += [
    "",
    "## 4. Scope and editorial exclusions (optional reversals)",
    "",
    "Excluded as editorials or commentary, or as not about athletes, sport or exercise. **Action:** none unless you "
    "disagree. To reverse one, say so and it will be re-drafted as INCLUDE in the next batch.",
    "",
]
for b, r in scope:
    out += [f"- **{r['sourceFile']}** ({b}): {short(r.get('exclusionReason'), 200)}"]
papers = json.load(open(f"{R}/papers.json", encoding="utf8"))
by_doi = {}
for paper in papers:
    doi = (paper.get("doi") or "").strip().lower()
    if doi:
        by_doi.setdefault(doi, []).append(paper)
collisions = {doi: group for doi, group in by_doi.items() if len(group) > 1}
out += [
    "",
    "## 5. Published records that share a DOI",
    "",
    "Two or more published records carry the same DOI. Either the records are duplicates of one article, or one "
    "record has the wrong DOI. **Action:** open each source; if they are the same article, say which ID to retire "
    "(IDs are never reused); if not, the wrong DOI will be corrected from the PDF in a follow-up batch.",
    "",
]
for doi, group in sorted(collisions.items()):
    out.append(f"- `{doi}`: " + "; ".join(f"ID {p['id']} ({short(p['citation'], 90)})" for p in group))
if not collisions:
    out.append("- None.")
open(f"{R}/docs/needs-eric.md", "w", encoding="utf8").write("\n".join(out) + "\n")
print(f"needs-eric.md: {len(mismatch)} mismatches, {len(degraded)} degraded, {len(scope)} scope calls, {len(collisions)} DOI collisions")
